=== AkimSaadi/Donn-es-Post-Relationnelles/Recettes.dtd
<!ELEMENT Recettes (recette | auteur | categoriePlat | sousCategoriePlat | produitIngredient | ingredient)*><!ELEMENT recette (titre, resumé?, photo, datePublication, difficulté, ingredients, nombrePersonne, tempsPréparation, tempsCuisson, tempsRepos, description?, note, ref-ingredient*, ref-sous-categorie, ref-auteur*)><!ELEMENT resumé (p)><!ELEMENT titre (#PCDATA)><!ELEMENT photo (#PCDATA)><!ELEMENT datePublication (#PCDATA)><!ELEMENT difficulté (#PCDATA)><!ELEMENT ingredients (ingredientRecette)*><!ELEMENT ingredientRecette (ref | quantite)*><!ELEMENT ref (#PCDATA)><!ELEMENT quantite (#PCDATA)><!ELEMENT ingredient (nom, apportNutritif, apportEnergetique, saison, description?, ref-recette*)><!ELEMENT nom (#PCDATA)><!ELEMENT apportNutritif (#PCDATA)><!ELEMENT apportEnergetique (#PCDATA)><!ELEMENT saison (#PCDATA)><!ELEMENT nombrePersonne (#PCDATA)><!ELEMENT tempsPréparation (#PCDATA)><!ELEMENT tempsCuisson (#PCDATA)><!ELEMENT tempsRepos (#PCDATA)><!ELEMENT description (p)><!ELEMENT p (#PCDATA | p | t | br)*><!ELEMENT t (#PCDATA)><!ELEMENT br EMPTY><!ELEMENT note (#PCDATA)><!ELEMENT auteur (nom, age, pays, sexe, biographie, ref-recette*)><!ELEMENT age (#PCDATA)><!ELEMENT pays (#PCDATA)><!ELEMENT sexe (#PCDATA)><!ELEMENT biographie (#PCDATA)><!ELEMENT ref-auteur EMPTY><!ELEMENT ref-recette EMPTY><!ELEMENT ref-ingredient EMPTY><!ELEMENT categoriePlat (nom, description)><!ELEMENT sousCategoriePlat (nom, description, nombreRecette, ref-categorie)><!ELEMENT nombreRecette (#PCDATA)><!ELEMENT produitIngredient (nom, ref-ingredient+)><!ELEMENT ref-categorie EMPTY><!ELEMENT ref-sous-categorie EMPTY><!ATTLIST recette	id ID #REQUIRED><!ATTLIST ingredient	id ID #REQUIRED><!ATTLIST produitIngredient	id ID #REQUIRED><!ATTLIST auteur	id ID #REQUIRED><!ATTLIST sousCategoriePlat	id ID #REQUIRED><!ATTLIST ref-auteur	ref IDREF #REQUIRED><!ATTLIST ref-recette	ref IDREF #REQUIRED><!ATTLIST ref-ingredient	ref IDREF #REQUIRED><!ATTLIST ref-sous-categorie	ref IDREF #REQUIRED><!ATTLIST categoriePlat	id ID #REQUIRED><!ATTLIST ref-categorie	ref IDREF #REQUIRED>

=== AkimSaadi/Donn-es-Post-Relationnelles/Recettes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Recettes SYSTEM "Recettes.dtd">
<Recettes>
	<recette id="r2830">
		<titre>Cake à la tomate farcie</titre>
		<resumé>
			<p>
				<t>Cake à la tomate farcie - Recettes de cuisine Ôdélices</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg</photo>
		<datePublication>2011-04-24</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>F120</ref>  <quantite>100g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>L300</ref>  <quantite>1 cuillère à café rase</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>L50</ref>  <quantite>7,5 cl</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>O12</ref>  <quantite>1</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>H20</ref>  <quantite>1 cuillère à soupe</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>t142</ref>  <quantite>1 petite boite </quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>F10</ref>  <quantite>30 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>t120</ref>  <quantite>6 grappes</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>S12</ref>  <quantite/>
			</ingredientRecette>
			<ingredientRecette>
				<ref>Po40</ref>  <quantite/>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>6</nombrePersonne>
		<tempsPréparation>20min</tempsPréparation>
		<tempsCuisson>25min</tempsCuisson>
		<tempsRepos/>
		<note/>
		<ref-ingredient ref="F120"/>
		<ref-ingredient ref="L300"/>
		<ref-ingredient ref="L50"/>
		<ref-ingredient ref="O12"/>
		<ref-ingredient ref="H20"/>
		<ref-ingredient ref="t142"/>
		<ref-ingredient ref="F10"/>
		<ref-ingredient ref="t120"/>
		<ref-ingredient ref="S12"/>
		<ref-ingredient ref="Po40"/>
		<ref-sous-categorie ref="SC1"/>
		<ref-auteur ref="AUT3"/>
	</recette>
	<recette id="r3136">
		<titre>Petits cakes au chèvre frais et myrtilles</titre>
		<resumé>
			<p>
				<t> Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdélices</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg</photo>
		<datePublication>2012-04-09</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>F120</ref>  <quantite>250 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>L50</ref>  <quantite>15cl</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>O12</ref>  <quantite>4</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>H20</ref>  <quantite>5cl</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>FC20</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>B200</ref>  <quantite>1/4 cuillerée à café</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>M110</ref>  <quantite>100 g</quantite>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>6</nombrePersonne>
		<tempsPréparation>10min</tempsPréparation>
		<tempsCuisson>17min</tempsCuisson>
		<tempsRepos/>
		<note>5</note>
		<ref-ingredient ref="F120"/>
		<ref-ingredient ref="L50"/>
		<ref-ingredient ref="O12"/>
		<ref-ingredient ref="H20"/>
		<ref-ingredient ref="FC20"/>
		<ref-ingredient ref="B200"/>
		<ref-ingredient ref="M110"/>
		<ref-sous-categorie ref="SC1"/>
		<ref-auteur ref="AUT2"/>
	</recette>
	<recette id="r4275">
		<titre>Mozzarella panée</titre>
		<resumé>
			<p>
				<t>Pour un soir de semaine, si vous voulez faire une salade express mais épatante, faites de la mozzarella panée ! C'est rapide, facile et très syma !
</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/mozzarella_panee.jpg</photo>
		<datePublication>2015-02-08</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>B10</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>O12</ref>  <quantite>1</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>F120</ref>  <quantite>4 cuillerées à soupe</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>CH12</ref>  <quantite>1 petit bol</quantite>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>4</nombrePersonne>
		<tempsPréparation>5min</tempsPréparation>
		<tempsCuisson>5min</tempsCuisson>
		<tempsRepos/>
		<note>5</note>
		<ref-ingredient ref="B10"/>
		<ref-ingredient ref="O12"/>
		<ref-ingredient ref="F120"/>
		<ref-ingredient ref="CH12"/>
		<ref-sous-categorie ref="SC2"/>
		<ref-auteur ref="AUT1"/>
	</recette>
	<recette id="r3289">
		<titre>Oeuf cocotte aux marrons</titre>
		<photo>http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg</photo>
		<datePublication>2012-11-22</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>M9</ref>  <quantite>200 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>O12</ref>  <quantite>4</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>C50</ref>  <quantite>4 cuillerées à soupe</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>S12</ref>  <quantite/>
			</ingredientRecette>
			<ingredientRecette>
				<ref>Po40</ref>  <quantite/>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>4</nombrePersonne>
		<tempsPréparation>5min</tempsPréparation>
		<tempsCuisson>15min</tempsCuisson>
		<tempsRepos/>
		<note/>
		<ref-ingredient ref="M9"/>
		<ref-ingredient ref="O12"/>
		<ref-ingredient ref="C50"/>
		<ref-ingredient ref="S12"/>
		<ref-ingredient ref="Po40"/>
		<ref-sous-categorie ref="SC2"/>
		<ref-auteur ref="AUT1"/>
	</recette>
	<recette id="r4315">
		<titre>Endives farcies au thon</titre>
		<resumé>
			<p>
				<t>

Une salade « hébergée » dans une feuille d'endive ! Une idée gourmande qui ravira les plus jeunes qui pourront d'ailleurs vous aider à farcir les endives !</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg</photo>
		<datePublication>2015-03-12</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>e300</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>t120</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>Co30</ref>  <quantite>6</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>C50</ref>  <quantite>2 cuillerées à soupe</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>M80</ref>  <quantite>2 cuillerées à soupe</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>CI10</ref>  <quantite>50 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>t142</ref>  <quantite>10 brins</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>S12</ref>  <quantite/>
			</ingredientRecette>
			<ingredientRecette>
				<ref>Po40</ref>  <quantite/>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>4</nombrePersonne>
		<tempsPréparation>15min</tempsPréparation>
		<tempsCuisson/>
		<tempsRepos/>
		<note/>
		<ref-ingredient ref="e300"/>
		<ref-ingredient ref="t120"/>
		<ref-ingredient ref="Co30"/>
		<ref-ingredient ref="C50"/>
		<ref-ingredient ref="M80"/>
		<ref-ingredient ref="CI10"/>
		<ref-ingredient ref="t142"/>
		<ref-ingredient ref="S12"/>
		<ref-ingredient ref="Po40"/>
		<ref-sous-categorie ref="SC3"/>
		<ref-auteur ref="AUT1"/>
	</recette>
	<recette id="r1241">
		<titre>Moules et frites</titre>
		<resumé>
			<p>
				<t>	

Si vous passez par le nord, prenez le temps de déguster des frites savoureuses dans une baraque à frites et n'oubliez pas de goûter à des moules de là-bas !
Recettes extraites du livre Craquez pour la cuisine des chtis !
</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/moules-frites.jpg</photo>
		<datePublication>2006-06-01</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>MO7</ref>  <quantite>2 à 3 litres</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>oi16</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>ech12</ref>  <quantite>2</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>CE5</ref>  <quantite>1</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>BEU1</ref>  <quantite>20 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>pom06</ref>  <quantite>1 kg</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>H20</ref>  <quantite/>
			</ingredientRecette>
			<ingredientRecette>
				<ref>S12</ref>  <quantite/>
			</ingredientRecette>
		</ingredients>
		<nombrePersonne>4</nombrePersonne>
		<tempsPréparation>15min</tempsPréparation>
		<tempsCuisson>30 min</tempsCuisson>
		<tempsRepos/>
		<note/>
		<ref-ingredient ref="MO7"/>
		<ref-ingredient ref="oi16"/>
		<ref-ingredient ref="ech12"/>
		<ref-ingredient ref="CE5"/>
		<ref-ingredient ref="BEU1"/>
		<ref-ingredient ref="pom06"/>
		<ref-ingredient ref="H20"/>
		<ref-ingredient ref="S12"/>
		<ref-sous-categorie ref="SC16"/>
		<ref-auteur ref="AUT4"/>
	</recette>
	<recette id="r2101">
		<titre>Gigot d'agneau au cumin</titre>
		<resumé>
			<p>
				<t>	

Pour la cuisson d'un gigot d'agneau, comptez environ 15 min par livre. Il sera rosé à coeur.

</t>
			</p>
		</resumé>
		<photo>http://www.odelices.com/images/recettes/gigot-d-agneau-au-cumin.jpg</photo>
		<datePublication>2009-02-09</datePublication>
		<difficulté>Très facile</difficulté>
		<ingredients>
			<ingredientRecette>
				<ref>a117</ref>  <quantite>1,5 kg</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>BEU1</ref>  <quantite>20 g</quantite>
			</ingredientRecette>
			<ingredientRecette>
				<ref>S12</ref>  <quantite/>
			</ingredientRecette>
			<ingredientRecette>
				<ref>Po40</ref>  <quantite/>
